language: python
python:
  - "3.7"
install:
  - pip install -r test-requirements.txt
script:
  - flake8 --max-line-length=100 --count --max-complexity=10 .
  - find . -iname "*.py" -exec pylint -r y --max-line-length=100 {} +